### ISSUE TITLE
Services using mtls are not able to reference a root CA

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#115]
If the property `services.ca_certificates` is specified, an error is returned `Tag Validation Errors: string indices must be integers, not 'str'`.

It should allow the `ca_certificates` to be set without error.

**Comment by rustyjux** [comment]
@ikethecoder wrote (in Jira):

> The other consideration too is that the gwa v2 CLI apply should handle GatewayCertificate as well as GatewayService.  So that the certificate can be registered as part of the same sync process.

We also identified the need for GatewayUpstream

and we will also require updates in `gwa-cli` to properly handle `upstreams`
