### ISSUE TITLE
Allow custom certificates to be used for routes

### ISSUE THREAD

**Issue by ikethecoder** [bcgov/gwa-api#125]
Due to the handling of 3rd party cookies in browsers, there is a requirement to allow custom domains to be configured on the Kong Gateway, as opposed to now where they have to use one of the wildcard-based certificates.

To accomplish this, we need:

1. a way for an API Provider to register a SSL/TLS certificate
    1. API Providers are able to register SSL/TLS certificates already for the purposes of performing mTLS between Kong and the Upstream service.  See: https://developer.gov.bc.ca/docs/default/component/aps-infra-platform-docs/how-to/upstream-services/#upstream-services-with-mtls
    1. confirm we can provide SNIs here
1. to enhance the `gateway API` to collect the certificate details from the Kong Admin API and including them in the request that goes to the `kube API`
    1. need to avoid host transformation for custom domains (https://github.com/bcgov/gwa-api/blob/dev/microservices/gatewayApi/v2/routes/gateway.py#L472)
    ```
    if is_host_custom_domain():
        new_hosts.append(host)
    ```
    1. need an attribute at the route level for certificates, key value pair where the key is the host and the value is the cert (all the cert data from admin API)
    1. add cert info to the route_payload, send all the certs for the namespace (or just `[]` if none)
1. update the `kube API` to use the new information about custom certificates and apply the Route with the appropriate SSL/TLS details
1. update `scheduler API` to gather information from the Kong Admin API and send it to the `kube API` for provisioning.
    1. as part of each sync, get all certs
    1. when sending routes to kubeAPI, if the route ends in a custom domain, match the cert using the SNI and send the cert data to kubeAPI
    1. if there isn't a match then throw an exception

## Manual validation

On top of automated tests in gwa-api microservices, can:

- register the *.api.gov.bc.ca cert in Kong and create a route to `webapps.gov.bc.ca` using the *.api.gov.bc.ca cert (it's also valid for `webapps`)
- curl with --resolve to Silver (or Gold)

A/C:
- API providers can create routes to custom domains
  - API providers can register a cert for custom domain and have that cert applied to routes created with that custom domain 
  - process is entirely self-serve / no action from APS is required for Gateways on Silver cluster

**Comment by rustyjux** [comment]
@SateeshFW test tag
[~71202062f08ee047a8430c985584d505dc0600] test tagging Saadan
