### ISSUE TITLE
When a namespace has been deleted via the gwa-api the project remains in keycloak

### ISSUE THREAD

**Issue by gjlawran** [bcgov/gwa-api#26]
As a user I would like to be able to fully delete any namespaces I no longer require so that I am not confused by those that are active and those that are inactive.  When a namespace is deleted the project is retained within the APS auth store (KeyCloak)  and displayed when a user logs in.

**Comment by ikethecoder** [comment]
It is true that the project remains in Keycloak (with an attribute of "decommissioned" but it should not be confusing to a user as it should not appear anywhere.  Can we reconfirm this issue?

**Comment by odyeung** [comment]
@ikethecoder please add stale -- automate it when no comments are in tickets

**Comment by rustyjux** [comment]
This can probably be closed - though I'm curious @ikethecoder, why don't we delete the group (and thus re-open the gatewayId for reuse) but instead just add the `decommissioned` attribute?
